#+TITLE: Website-Refactor( Website-Refactor( ...))
#+DATE: <2024-06-12 Wed>

I wonder how much time I will waste cumulatively remaking my website.
I've decided to start formally marking down my thoughts when I change it to double down on the wasting time.

I've established [[../personal_websites_are_dumb/][personal websites are dumb]], but here I am again; another year, another website refactor.

My enthusiasm for emacs led me to look into Emacs Lisp which caused a [[../../../Articles/Programming/a-lispy-interlude/][deep dive into the very interesting world of lisp]]

Python was previously used to glue all the exported html together and I've decided to switch to Common Lisp
(There /might/ be some good reasons for this:
more expressive, ANSI standard, lindy, etc. but really I was just curious / wanted to challenge myself to learn something new. I also
really came around to the Lambda Calculus style/ s-expressions. Surely not worth the time investment, but what is?)

The more anachronistic and inscrutable the better I guess.
It is nice to be able to permanently live in emacs.
And yet, and yet...:

#+BEGIN_QUOTE
There are two ways to write error-free programs; only the third one works.
- Alan Perlis
#+END_QUOTE





