#+TITLE: Personal Websties Are Dumb
#+DATE: <2022-11-21 Mon>
#+FILETAGS: :Opinion:

This is [[http://number-none.com/blow/blog/][Jonathan Blow's Website]]; need I say more? (Extended commentary can be found [[https://motherfuckingwebsite.com/][here]])

[[https://www.youtube.com/watch?v=tHEOGrkhDp0][Advertizing is almost always bad]] (At a minimum it's unsubstantive/ empty.)
And, most of the time, especially with younger people (or people who do not have a well developed career), personal websites are just personal advertising. 


# Jon Blow has made some incredible games and that is all the endorsement/ advertisement / marketing he and his team will ever need. 
# He's proven himself to his peers and created a rent free presence in the minds of gamers around the world. 
# Who cares what his website looks like?

Jon Blow is a proven, world-class programmer and designer, but we all can't be Jon Blow.

Enter the personal portfolio (a website being part of that).

In line with skill and credentialing inflation, a well developed (I should say superficially pleasing) portfolio is (counterproductively) required for a job nowadays.
(But wait, wasn't that what college was for? Why did I study so hard and stress out so much if that doesn't count as a general vetting process of baseline competence?
— Gute Frage nächste Frage.)

It's a strange, boring dystopia/ kafka-esque moment when you're being interviewed for a technical skill by someone who doesn't have said technical skill and
they're judging you primarily and negatively for the plainness of your portfolio website.
(This is disappointing for both parties, while Jon Blow is anecdotal, I do geuinely think website excessiveness is in fact usually inversly related with ability
(with some notable exceptions like [[http://acko.net][Steven Witten]]), I assume they want the best engineer possible and I want to waste as little time as possible)

I could try to make a fanicer website ([[https://zackmibrown.github.io/][here's one]] I made for a friend) but it's ultimately disaptive for non-renewable resources like time and
attention which we're all rapidly running out of.

Wouldn't we all rather be writing stories, making games or solving interesting & real problems instead?

Moreover, isn't it, as said above, counterproductive to a real portfolio to spend said resources on something that ultimately has nothing to do with the skills and
knowledge you're trying to hone?

Historically, I've tended to remake my website about once a year (revist resume, tidy up etc)
and this year is no different. (Emacs has become my main text editor and so another
website iteration using org mode seemed prudent), but I'm done doing anything beyond content (anything superfluous that I don't find interesting or care about).

Just minimal styling and a barebones static site from here on out.
(I still want slightly more control and customizable workflow than an SSG framework allows otherwise I'd just do that. Also, they can also be
complicated to maintain, usually have a lot of dependencies and break over time)

Maintenance is a contraint with a concomitant cost and I'm just not willing to pay it for something as insignificant as a personal website.

If there's a silver lining, maybe this is lesson that's transferable to other things that have incurred a heavy maintenance cost, accepting and hacking ontop of rather
than reinventing the various technical black boxes[fn:1] that may come.

Maybe this is finally *how I learn to stop worrying and love not reinventing the wheel.*

[fn:1]
#+BEGIN_QUOTE
The Black Box Abstraction is key to all of science, engineering, computing, and in fact to civilization itself.
A result once established can be used without knowing how the result was achieved.
Once a black box has been verified, I can rely on that black box to satisfy its specification.
Analogy: in mathematics, we can rely on an accepted theorem without proving the theorem all over again. -- [[https://www.quora.com/profile/Jamie-Lawson-5][Jamie Lawson]]
#+END_QUOTE


