#+STARTUP: indent
#+TITLE: WebGL: Pushing Pixels
#+DATE: 02.07.2021

*A Small project post mortem*

Tl;dr: check it out [[../../../../../rsc/projects-tools-demos/Projects/JS-&-WebGL/collision_study/refactor/][here]]

* Overview:
---------------------------------------------------------------------------------------

** Motivation
---------------------------------------------------------------------------------------
I wanted to make a simple physics "engine" (equations of motion, basic collision) as an exercise 

I was inspired to do so after watching this presentation by [[https://www.youtube.com/watch?v=Zkx1aKv2z8o&t=2399s][Steven Witten]]
It's worth your time if you're interested in math or graphics
All his presentations, along with a host of interesting toys and articles, can be found on his [[http://acko.net/][incredibly polished site]]

The Gist
---------------------------------------------------------------------------------------
The fundamental idea of a physics system is very simple: incoporate the appropriate physical law (gravity, hookes law, w/e) and numerically integrate.

Pushing around pixels in practice however is hard with a capital H and this is just a simulation of frictionless colliding rigid bodies (no rotation, multiple contact point collisions, or constrained simulation)

As usual, the underpinning rendering and programming routines were all implemented from scratch (webgl, seperating axis theorem, impulse collision response, euler integration etc)

In the future, time/ interest willing, I hope to improve upon this first stab and dig deeper into the subject.

* Rendering Side of Things:
---------------------------------------------------
- Vanilla WebGL with some boilerplate code and glMatrix as my vector and matrix library.

- Wireframe shader via barycentric coordinates from vertices.

A glaring missing component is not setting current state of renderer from the interpolation between the two physics states.
This results in some flickering artifacts.
Also, if I were to do this as a fuller project I'd like to add instancing/ batch rendering to be able to stress test the simulation.

* Programming Side of Things:
---------------------------------------------------
Visualization tests or articles for each main component:

+ Euler integration for numerical integration to propagate motion:
   - [[../../Math/euler_method/][Euler Method Article]]

+ Quad tree + circle colliders for broadphase detection & seperating axis theorem for narrow phase detection + generating contact normal for impulse
   - [[../../Physics/impulse_based_collision][My Impulse Based Collision Response Article]]
   - [[../../../Projects/2D_physics/SATVisualization/][Seperating Axis Theorem Test in p5]]
   - [[../../../Projects/2D_physics/quadTreeVisualization/][Quadtree test in p5]]

* Resources:
---------------------------------------------------------------------------------------

+ Fixed Timestep:
   - [[https://www.gafferongames.com/post/fix_your_timestep/][Glenn Fiedler]]

+ SAT:
   - [[https://dyn4j.org/2010/01/sat/][SAT tutorial by dyn4j]]
   - [[http://www.metanetsoftware.com/technique/tutorialA.html][Tutorial by n++ developer]]

+ Impulse Based Collision Response:
   - [[https://www.amazon.com/Game-Physics-Engine-Development-Commercial-Grade/dp/0123819768][Ian Millington - Game Physics Engine Development]]
   - [[https://gamedevelopment.tutsplus.com/tutorials/how-to-create-a-custom-2d-physics-engine-the-basics-and-impulse-resolution--gamedev-6331?_ga=2.64050476.205125146.1625069373-736815224.1612468891][Randy Gaul - [[How to Create a Custom 2D Physics Engine: The Basics and Impulse Resolution]]]]
   - [[https://graphics.stanford.edu/courses/cs468-03-winter/Papers/ibsrb.pdf][Brian Mirtich & John Canny - Impulse-based Simulation of Rigid Bodies]]

+ Quadtree:
   - [[https://en.wikipedia.org/wiki/Quadtree#Pseudocode][Wikipedia]]
   - [[https://www.youtube.com/watch?v=OJxEcs0w_kE][The Coding Train]]
