#+STARTUP: indent
#+TITLE: About

Greetings and salutations, I'm Ian and this a small archive for things I become interested in (think poor man [[http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html"][Hyperphysics]] or [[https://www.algorithm-archive.org][Algorithm Archive]]).

I studied Physics (B.S.) and Math (B.S) and Mechanical Engineering (almost B.S) and I'm a hobbyist graphics programmer & game developer.

I'm motivated by understanding how things work and communicating ideas.

#+BEGIN_QUOTE
Writing doesn't just communicate ideas; it generates them.
-- Paul Graham
#+END_QUOTE

I find writing useful as scaffolding for synthetic, creative activities (learning something new or cataloging derivations mostly)
and sometimes that process turns into a full post here.

Unfortunately, I don't always have the time to proof read each post as thoroughly as I'd like *-*
I'm sure there are lots of spelling and grammar mistakes, but hopefully there aren't too many technical ones.

Thanks for stopping by and feel free to reach out. 

Cheers. 
