#+TITLE: Quotes
#+DATE: <2022-02-26 Sat>

Like the information density of a picture compared with words, I find quotes to be useful in communicating a great deal
with very little.

#+BEGIN_QUOTE
Try not to become a man of success, but rather try to become a man of value. -- Albert Einstein
#+END_QUOTE

#+BEGIN_QUOTE
What I cannot create, I do not understand. -- Richard Feynman
#+END_QUOTE

#+BEGIN_QUOTE
Was Du ererbt von deinen Vätern hast, erwirb es, um es zu besitzen. -- Goethe
#+END_QUOTE

#+BEGIN_QUOTE
Ostinato Rigore. -- Leonardo da Vinci
#+END_QUOTE

#+BEGIN_QUOTE
Only the autodidacts are free. -- Nassim Nicholas Taleb
#+END_QUOTE

#+BEGIN_QUOTE
Herd thither, me hither. -- Erik Naggum
#+END_QUOTE

#+BEGIN_QUOTE
"The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts." -- Bertrand Russell
#+END_QUOTE

#+BEGIN_QUOTE
The fool doth think he is wise, the wise man knows himself to be a fool -- William Shakespeare
#+END_QUOTE

#+BEGIN_QUOTE
If I am not for myself, who will be for me? And being for myself, what am I? And if not now, when? -- Hillel the Elder
#+END_QUOTE

#+BEGIN_QUOTE
There is only one thing that I dread: not to be worthy of my sufferings. -- Fyodor Dostoevsky
#+END_QUOTE

#+BEGIN_QUOTE
Arise awake and stop not until the goal is reached. -- Swami Vivekananda
#+END_QUOTE

#+BEGIN_QUOTE
The great appear great because we are on our knees. Let us rise! -- James Larkin
#+END_QUOTE

#+BEGIN_QUOTE
la nature ne fait jamais des sauts -- Leibniz
#+END_QUOTE

#+BEGIN_QUOTE
Wahrlich, es ist nicht das Wissen, sondern das Lernen, nicht das Besitzen sondern das Erwerben, nicht das Da-Seyn, sondern das Hinkommen, was den grössten Genuss. -- Gauss
#+END_QUOTE

#+BEGIN_QUOTE
When I write a paper, I have to rederive for myself the rules of differentiation and sometimes even the commutative law of multiplication. -- Lipót Fejér 
#+END_QUOTE

#+BEGIN_QUOTE
Hat man sein warum? des Lebens, so verträgt man sich fast mit jedem wie? -- Nietzsche
#+END_QUOTE

#+BEGIN_QUOTE
The only true wisdom is in knowing you know nothing. -- Socrates
#+END_QUOTE

#+BEGIN_QUOTE
The unexamined life is not worth living. -- Socrates
#+END_QUOTE

#+BEGIN_QUOTE
Practice yourself, for heaven’s sake, in little things;
and thence proceed to greater. -- Epictetus
#+END_QUOTE

#+begin_quote
"Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away." -- Atoine de Saint-Exupery
#+end_quote

#+begin_quote
Give them the third best to go on with; the second best comes too late, the best never comes. -- Robert Alexander Watson-Watt
#+end_quote

#+begin_quote
"Make things as simple as possible, but no simpler." -- Abert Einstein
#+end_quote

#+begin_quote
There are two ways to write error-free programs; only the third one works. -- Alan Perlis
#+end_quote

#+begin_quote
"The truth is that the State is a conspiracy designed not only to exploit, but above all to corrupt its citizens" -- Leo Tolstoy
#+end_quote

#+begin_quote
"Part of the fame of the most celebrated people always belongs to the foolishness of their admirers" -- Georg Christoph Lichtenberg
#+end_quote

#+BEGIN_QUOTE
The secret to what anything means to us depends on how we've connected it to other things we know. -- Marvin Minsky
#+END_QUOTE

#+BEGIN_QUOTE
And that's the point – Not to make something sell, something very popular, 
but to love something, and make something that we creators can love.
It's the very core feeling we should have in making games. -- Shigeru Miyamoto
#+END_QUOTE

#+BEGIN_QUOTE
If you ask me, Tech/Engineering is there to support Art/Design. And Art/Design is there to support Story/Experience/Product. Science/Research is there to inspire them all. -- Inigo Quilez
#+END_QUOTE

#+BEGIN_QUOTE
Ever tried. Ever failed. No matter. Try again. Fail again. Fail better. -- Samuel Beckett
#+END_QUOTE

#+BEGIN_QUOTE
Vīta brevis,
ars longa,
occāsiō praeceps,
experīmentum perīculōsum,
iūdicium difficile.
#+END_QUOTE









